type EventDetails = {
  additional_ticket_timer: number;
  additional_venue_details: string | null;
  additional_venue_details_rich_text: string | null;
  allowed_payment_methods: number[];
  business_address: string | null;
  business_name: string | null;
  cards_pg_percentage: number;
  checkout_consent: string;
  checkout_footer_icon: string;
  city: string | null;
  collect_gst_details: string | null;
  country: string | null;
  currency_id: number;
  currency_name: string;
  description: string;
  email_campaign_architecture: number;
  enable_face_recognition: boolean;
  end_date: string;
  end_time: string;
  event_facebook_url: string | null;
  event_id: string;
  event_linkedin_url: string | null;
  event_live_link: string;
  event_poster_url: string;
  event_short_name: string;
  event_template: number;
  event_twitter_url: string | null;
  event_url: string;
  event_website: string;
  expected_attendees: number;
  expected_speakers: string | null;
  facebook_pixel_code: string | null;
  fav_icon_urls: {
    [key: string]: string;
  };
  first_ticket_timer: number;
  google_analytics_code: string | null;
  has_agenda: boolean;
  has_coupons: boolean;
  has_speakers: boolean;
  has_sponsors: boolean;
  has_workshops: boolean;
  invoice_footer_icon: string;
  is_free: boolean;
  is_pg_charge_inclusive: boolean;
  is_running_on_kh: boolean;
  is_tax_inclusive: boolean;
  is_tax_on_pg_inclusive: boolean;
  is_taxable: boolean;
  is_virtual: boolean;
  keywords: string[];
  kh_percentage: number;
  latitude: number | null;
  longitude: number | null;
  max_team_members: number;
  min_team_members: number;
  name: string;
  navbar_icon: string;
  net_banking_pg_percentage: number;
  no_of_workshops: number;
  non_inr_pg_percentage: number;
  old_tax_invoice_implementation: boolean;
  organiser_country_code: string;
  organiser_dial_code: string;
  organiser_email: string;
  organiser_image_url: string;
  organiser_info: string;
  organiser_name: string;
  organiser_phone: string;
  organiser_website: string;
  organizer_facebook_url: string;
  organizer_linkedin_url: string;
  organizer_twitter_url: string;
  poster_thumbnail: string;
  redirection_url: string | null;
  redirection_url_timeout: number;
  sender_email: string | null;
  speaker_section_description: string;
  speaker_section_title: string;
  sponsor_categories_enabled: boolean;
  sponsor_section_description: string;
  sponsor_section_title: string;
  start_date: string;
  start_time: string;
  state: string | null;
  stripe_cards_pg_percentage: number;
  tax_consent: string;
  tax_country: string;
  tax_name: string;
  tax_percentage: number;
  tax_percentage_on_pg: number;
  ticket_footer_icon: string;
  time_zone: string;
  upi_pg_percentage: number;
  venue: string | null;
  wallet_pg_percentage: number;
  workshop_section_description: string;
  workshop_section_title: string;
};
